// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWMPTW3yt-aAhTLWQgh50JSXaQMIuebQY',
    appId: '1:689529970512:web:7ffedf58f2d4ddafaa9655',
    messagingSenderId: '689529970512',
    projectId: 'task-manager-phuc',
    authDomain: 'task-manager-phuc.firebaseapp.com',
    databaseURL: 'https://task-manager-phuc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-phuc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrjGRR9OxcIMLdHtxWbYf2yX3HOop47oM',
    appId: '1:689529970512:android:7596aedd57c5d77faa9655',
    messagingSenderId: '689529970512',
    projectId: 'task-manager-phuc',
    databaseURL: 'https://task-manager-phuc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-phuc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHL_YFEI7s4AcZHmnQ-v7DFP_97wqIcC0',
    appId: '1:689529970512:ios:e3aa5bb7ef04c40caa9655',
    messagingSenderId: '689529970512',
    projectId: 'task-manager-phuc',
    databaseURL: 'https://task-manager-phuc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-phuc.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHL_YFEI7s4AcZHmnQ-v7DFP_97wqIcC0',
    appId: '1:689529970512:ios:e3aa5bb7ef04c40caa9655',
    messagingSenderId: '689529970512',
    projectId: 'task-manager-phuc',
    databaseURL: 'https://task-manager-phuc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-phuc.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWMPTW3yt-aAhTLWQgh50JSXaQMIuebQY',
    appId: '1:689529970512:web:a14bc6ad02eb0248aa9655',
    messagingSenderId: '689529970512',
    projectId: 'task-manager-phuc',
    authDomain: 'task-manager-phuc.firebaseapp.com',
    databaseURL: 'https://task-manager-phuc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-phuc.firebasestorage.app',
  );

}